services:
  - type: web
    name: forever-boutique
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FB_VERIFY_TOKEN
        sync: false
      - key: FB_PAGE_ACCESS_TOKEN
        sync: false
      - key: FB_APP_SECRET
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: ENVIRONMENT
        value: production 